REQUIRED_COLUMNS = ("drug_name", "target", "efficacy")

MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024  # 10 MB, matches the S3 presigned POST content-length-range
MAX_ROWS = 50_000
MAX_FIELD_LENGTH = 255
EFFICACY_MIN = 0.0
EFFICACY_MAX = 100.0
MAX_STORED_ERRORS = 100

PRESIGNED_URL_EXPIRY_SECONDS = 300  # 5 minutes
RECORDS_PAGE_SIZE = 50
MAX_RECORDS_PAGE_SIZE = 200
UPLOADS_PAGE_SIZE = 20
MAX_UPLOADS_PAGE_SIZE = 100

UPLOADS_TABLE_NAME_ENV_VAR = "UPLOADS_TABLE_NAME"
RECORDS_TABLE_NAME_ENV_VAR = "RECORDS_TABLE_NAME"
UPLOAD_BUCKET_NAME_ENV_VAR = "UPLOAD_BUCKET_NAME"
